
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue Feb 09 16:10:37 CET 2021
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CONST = 26;
  public static final int NUMCONST = 40;
  public static final int CASE = 31;
  public static final int LPAREN = 6;
  public static final int SEMI = 5;
  public static final int CONTINUE = 29;
  public static final int MINUS = 17;
  public static final int RPAREN = 7;
  public static final int COMMA = 10;
  public static final int DDOT = 22;
  public static final int CLASS = 25;
  public static final int INC = 23;
  public static final int DIV = 19;
  public static final int PLUS = 13;
  public static final int IF = 34;
  public static final int EOF = 0;
  public static final int RETURN = 12;
  public static final int EQUAL = 15;
  public static final int NEW = 27;
  public static final int error = 1;
  public static final int MUL = 18;
  public static final int MOD = 20;
  public static final int IDENT = 41;
  public static final int BREAK = 28;
  public static final int VOID = 16;
  public static final int SWITCH = 30;
  public static final int ELSE = 35;
  public static final int LBRACE = 3;
  public static final int ENUM = 36;
  public static final int READ = 14;
  public static final int CHARCONST = 38;
  public static final int WHILE = 33;
  public static final int RBRACE = 4;
  public static final int BOOLCONST = 39;
  public static final int EXTENDS = 37;
  public static final int PROG = 2;
  public static final int LSQUAR = 8;
  public static final int TER = 21;
  public static final int DEC = 24;
  public static final int RSQUAR = 9;
  public static final int PRINT = 11;
  public static final int DO = 32;
}

